from . import (patient,
               doctor,
               diagnosis,
               patient_card,
               disease,
               disease_category,
               contact_person,
               visit_doctor,
               personal_doctor_history,
               )
