from . import (patient,
               doctor,
               diagnosis,
               patient_card,
               disease,
               disease_category,
               contact_person,
               visit_doctor,
               personal_doctor_history,
               type_of_research,
               type_of_research_category,
               type_of_sample,
               research,
               schedule_of_doctor,
               )
